repos:
-   repo: https://github.com/pycqa/flake8
    rev: 3.9.0
    hooks:
    -   id: flake8
        exclude: project/app/app.py
        args: ['--config=setup.cfg']
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.8.0
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: detect-private-key