#From https://towardsdatascience.com/docker-for-python-dash-r-shiny-6097c8998506

FROM python:3.8

LABEL maintainer "Robin Opdam, robinopdam@hotmail.com"

WORKDIR /code

COPY requirements.txt /

ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
RUN pip install -r /requirements.txt

COPY ./ ./

ENV ENVIRONMENT prod
ENV TESTING 0

CMD gunicorn --bind 0.0.0.0:$PORT app.main:app -k uvicorn.workers.UvicornWorker