name: Code Quality

on: [push]

jobs:
  lint:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
      with:
      python-version: "3.8"
    - name: install flake8
      run: pip install flake8==3.8.4
    - name: flake8
      run: python -m flake8 .